name: rl2grid-39
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch=2.2.0
  - cpuonly 
  - tensorboard
  - wandb
  - gymnasium=0.29.1
  - stable-baselines3=2.3.2
  - scipy=1.11.3
  